language: node_js
node_js:
  - '0.10'
rvm:
  - 2.0.0

install:
  - npm install
  - ./node_modules/bower/bin/bower install

addons:
  sauce_connect: true

env:
  global:
  - secure: LOcLzSfOYmwkA+Xec4MRRGtIwGvz6MlGJ6NsLbPjeuPl8qkWK8oejkAlKWfSDavTcsyQUUuAoSxrmzGdAmw7UOnQnwuoERrxCQy4DoBf1X/zaWtkbOoF3mE1S+y/Fz5VyUsMJXCVxtQ6km2J37/YlIRfJFyD/qA3asqABZEIDPk=
  - secure: QCAg5KGls45EQ5MwIEIEYohEmGiEPFwrfcdHSMQAxDxkPVcZMNroX96anysULFEwm/kCiKkBwLNik6Ic3kNdi5bQMf6d+BBDA57yicPcXeCr6KS6jtCn52w/WinbLraotc5GOry/dGHqYCGBprQhXpR4O4sydSznH+izhehOOHw=
